



 


package com.wings.adapter;

import com.ibatis.dao.client.DaoManager;
import com.wings.dao.ShipperDAO;
import com.wings.ibatis.DaoConfig;
import com.wings.persistence.Shipper;
import com.wings.persistence.ShipperKey;
import com.wings.web.struts.forms.ShipperForm;
import java.util.List;
import java.util.ArrayList;
import org.apache.commons.beanutils.BeanUtils;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of cmp20. 
 * It has a set of methods to handle persistence for Shipper data (i.e. 
 * com.wings.web.struts.ShipperForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsShipperDelegate {


   /**
    * Create a new com.wings.web.struts.ShipperForm object and persist (i.e. insert) it.
    *
    * @param   shipperForm   The object containing the data for the new com.wings.web.struts.ShipperForm object
    * @exception   Exception   If the new com.wings.web.struts.ShipperForm object cannot be created or persisted.
    */
   public static com.wings.web.struts.forms.ShipperForm create (com.wings.web.struts.forms.ShipperForm shipperForm) throws Exception {
      Shipper shipper = new Shipper();  
      BeanUtils.copyProperties(shipper, shipperForm);
      shipper.setIdShipper(shipper.getIdShipper().replaceAll("&",""));
      ShipperDAO shipperDAO;
      DaoManager daoMgr = DaoConfig.getDaoManager();   
      shipperDAO = (ShipperDAO)daoMgr.getDao(ShipperDAO.class);      
      shipperDAO.insert(shipper);
      return shipperForm;
   }

   /**
    * Update (i.e. persist) an existing com.wings.web.struts.ShipperForm object.
    *
    * @param   shipperForm   The com.wings.web.struts.ShipperForm object containing the data to be updated
    * @exception   Exception   If the com.wings.web.struts.ShipperForm object cannot be updated/persisted.
    */
   public static com.wings.web.struts.forms.ShipperForm update (com.wings.web.struts.forms.ShipperForm shipperForm) throws Exception {
      Shipper shipper = new Shipper();  
      BeanUtils.copyProperties(shipper, shipperForm);
      ShipperDAO shipperDAO;
      DaoManager daoMgr = DaoConfig.getDaoManager();   
      shipperDAO = (ShipperDAO)daoMgr.getDao(ShipperDAO.class);      
      shipperDAO.updateByPrimaryKey(shipper);
      return shipperForm;
   }

   /**
    * Retrieve an existing com.wings.web.struts.ShipperForm object for editing.
    *
    * @param   shipperForm   The com.wings.web.struts.ShipperForm object containing the data used to retrieve the object (i.e. the primary key info).
    * @exception   Exception   If the com.wings.web.struts.ShipperForm object cannot be retrieved.
    */
   public static com.wings.web.struts.forms.ShipperForm edit (com.wings.web.struts.forms.ShipperForm shipperForm) throws Exception {
      ShipperKey shipperKey = new ShipperKey();  
      shipperKey.setIdShipper(shipperForm.getIdShipper());      
      ShipperDAO shipperDAO;
      DaoManager daoMgr = DaoConfig.getDaoManager();   
      shipperDAO = (ShipperDAO)daoMgr.getDao(ShipperDAO.class);      
      Shipper shipper = shipperDAO.selectByPrimaryKey(shipperKey);  
      try {
          BeanUtils.copyProperties(shipperForm, shipper);
      } catch (Exception e) {
          
      }      
      return shipperForm;
   }

   public static com.wings.web.struts.forms.ShipperForm findByName (com.wings.web.struts.forms.ShipperForm shipperForm) throws Exception {
      Shipper shipper = new Shipper();  
      shipper.setName(shipperForm.getName());      
      ShipperDAO shipperDAO;
      DaoManager daoMgr = DaoConfig.getDaoManager();   
      shipperDAO = (ShipperDAO)daoMgr.getDao(ShipperDAO.class);      
      shipper = shipperDAO.selectByIdName(shipper);  
      try {
          BeanUtils.copyProperties(shipperForm, shipper);
      } catch (Exception e) {
          
      }      
      return shipperForm;
   }

   /**
    * Remove (delete) an existing com.wings.web.struts.ShipperForm object.
    *
    * @param   shipperForm   The com.wings.web.struts.ShipperForm object containing the data to be deleted.
    * @exception   Exception   If the com.wings.web.struts.ShipperForm object cannot be removed.
    */  
   public static void remove (com.wings.web.struts.forms.ShipperForm shipperForm) throws Exception {
      ShipperKey shipperKey = new ShipperKey();  
      shipperKey.setIdShipper(shipperForm.getIdShipper());      
      ShipperDAO shipperDAO;
      DaoManager daoMgr = DaoConfig.getDaoManager();   
      shipperDAO = (ShipperDAO)daoMgr.getDao(ShipperDAO.class);      
      shipperDAO.deleteByPrimaryKey(shipperKey);      
   }

   /**
    * Retrieve all existing com.wings.web.struts.ShipperForm objects.
    *
    * @exception   Exception   If the com.wings.web.struts.ShipperForm objects cannot be retrieved.
    */
   public static List findAll (ShipperForm shipperForm) throws Exception {
      List retVals = new ArrayList();
      Shipper shipper = new Shipper();
      if (shipperForm!=null) {
          if (shipperForm.getName()!=null) {
              shipper.setName(shipperForm.getName()+"%");
          } else {
              shipper.setName("%");
          }
      } else {
          shipper.setName("%");
      }
      ShipperDAO shipperDAO;
      DaoManager daoMgr = DaoConfig.getDaoManager();   
      shipperDAO = (ShipperDAO)daoMgr.getDao(ShipperDAO.class);      
      retVals = (List)shipperDAO.selectAll(shipper);      
      return retVals;
   }

   public static List findName (String name) throws Exception {
      List retVals = new ArrayList();
      Shipper shipper = new Shipper();
      shipper.setName(name);
      ShipperDAO shipperDAO;
      DaoManager daoMgr = DaoConfig.getDaoManager();   
      shipperDAO = (ShipperDAO)daoMgr.getDao(ShipperDAO.class);      
      retVals = (List)shipperDAO.selectByName(shipper);
      return retVals;
   }

   
   /**
    * Retrieve a set of existing com.wings.web.struts.ShipperForm objects for editing.
    *
    * @param   shipperForm   The com.wings.web.struts.ShipperForm object containing the data used to retrieve the objects (i.e. the criteria for the retrieval).
    * @exception   Exception   If the com.wings.web.struts.ShipperForm objects cannot be retrieved.
    */
   public static List select (com.wings.web.struts.forms.ShipperForm shipperForm) throws Exception {
      List retVals = new ArrayList();
      
      return retVals;
   }

}
