



 


package com.wings.adapter;

import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;

/**
 * This is a delegate class to handle interaction with the backend persistence layer of cmp20. 
 * It has a set of methods to handle persistence for Jobtype data (i.e. 
 * com.wings.web.struts.JobtypeForm objects).
 * 
 * @author <strong>Generated by Middlegen.</strong>
 */
public class StrutsJobtypeDelegate {


   /**
    * Create a new com.wings.web.struts.JobtypeForm object and persist (i.e. insert) it.
    *
    * @param   jobtypeForm   The object containing the data for the new com.wings.web.struts.JobtypeForm object
    * @exception   Exception   If the new com.wings.web.struts.JobtypeForm object cannot be created or persisted.
    */
   public static com.wings.web.struts.forms.JobtypeForm create (com.wings.web.struts.forms.JobtypeForm jobtypeForm) throws Exception {
     
      return jobtypeForm;
   }

   /**
    * Update (i.e. persist) an existing com.wings.web.struts.JobtypeForm object.
    *
    * @param   jobtypeForm   The com.wings.web.struts.JobtypeForm object containing the data to be updated
    * @exception   Exception   If the com.wings.web.struts.JobtypeForm object cannot be updated/persisted.
    */
   public static com.wings.web.struts.forms.JobtypeForm update (com.wings.web.struts.forms.JobtypeForm jobtypeForm) throws Exception {
      
      return jobtypeForm;
   }

   /**
    * Retrieve an existing com.wings.web.struts.JobtypeForm object for editing.
    *
    * @param   jobtypeForm   The com.wings.web.struts.JobtypeForm object containing the data used to retrieve the object (i.e. the primary key info).
    * @exception   Exception   If the com.wings.web.struts.JobtypeForm object cannot be retrieved.
    */
   public static com.wings.web.struts.forms.JobtypeForm edit (com.wings.web.struts.forms.JobtypeForm jobtypeForm) throws Exception {
      
      return jobtypeForm;
   }

   /**
    * Remove (delete) an existing com.wings.web.struts.JobtypeForm object.
    *
    * @param   jobtypeForm   The com.wings.web.struts.JobtypeForm object containing the data to be deleted.
    * @exception   Exception   If the com.wings.web.struts.JobtypeForm object cannot be removed.
    */  
   public static void remove (com.wings.web.struts.forms.JobtypeForm jobtypeForm) throws Exception {
     
   }

   /**
    * Retrieve all existing com.wings.web.struts.JobtypeForm objects.
    *
    * @exception   Exception   If the com.wings.web.struts.JobtypeForm objects cannot be retrieved.
    */
   public static List findAll () throws Exception {
      List retVals = new ArrayList();
      
      return retVals;
   }

   /**
    * Retrieve a set of existing com.wings.web.struts.JobtypeForm objects for editing.
    *
    * @param   jobtypeForm   The com.wings.web.struts.JobtypeForm object containing the data used to retrieve the objects (i.e. the criteria for the retrieval).
    * @exception   Exception   If the com.wings.web.struts.JobtypeForm objects cannot be retrieved.
    */
   public static List select (com.wings.web.struts.forms.JobtypeForm jobtypeForm) throws Exception {
      List retVals = new ArrayList();
      
      return retVals;
   }

}
