package com.wings.dao;

import com.wings.persistence.Jobtype;
import com.wings.persistence.JobtypeKey;

public interface JobtypeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table jobtype
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    void insert(Jobtype record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table jobtype
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    int updateByPrimaryKey(Jobtype record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table jobtype
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table jobtype
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    Jobtype selectByPrimaryKey(JobtypeKey key);

    
    int deleteByPrimaryKey(JobtypeKey key);
}
