package com.wings.persistence;


public class AccountKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account.idAccount
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    private String idAccount;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account.idAccount
     *
     * @return the value of account.idAccount
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public String getIdAccount() {
        return idAccount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account.idAccount
     *
     * @param idAccount the value for account.idAccount
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public void setIdAccount(String idAccount) {
        if (idAccount != null) {
            idAccount = idAccount.trim();
        }
        this.idAccount = idAccount;
    }
}
