package com.wings.persistence;


public class AccountExample extends Account {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    private int idAccount_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    private int accountName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    private int category_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    private int type_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    private int saldoAwal_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public int getIdAccount_Indicator() {
        return idAccount_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public void setIdAccount_Indicator(int idAccount_Indicator) {
        this.idAccount_Indicator = idAccount_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public int getAccountName_Indicator() {
        return accountName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public void setAccountName_Indicator(int accountName_Indicator) {
        this.accountName_Indicator = accountName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public int getCategory_Indicator() {
        return category_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public void setCategory_Indicator(int category_Indicator) {
        this.category_Indicator = category_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public int getType_Indicator() {
        return type_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public void setType_Indicator(int type_Indicator) {
        this.type_Indicator = type_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public int getSaldoAwal_Indicator() {
        return saldoAwal_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table account
     *
     * @abatorgenerated Thu Jul 03 00:04:40 ICT 2008
     */
    public void setSaldoAwal_Indicator(int saldoAwal_Indicator) {
        this.saldoAwal_Indicator = saldoAwal_Indicator;
    }
}
