package com.wings.persistence;


public class AgentsKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column agents.idAgent
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String idAgent;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column agents.idAgent
     *
     * @return the value of agents.idAgent
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getIdAgent() {
        return idAgent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column agents.idAgent
     *
     * @param idAgent the value for agents.idAgent
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdAgent(String idAgent) {
        if (idAgent != null) {
            idAgent = idAgent.trim();
        }
        this.idAgent = idAgent;
    }
}
