package com.wings.persistence;


public class AgentfeeKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column agentfee.idAgentFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idAgentFee;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column agentfee.idAgentFee
     *
     * @return the value of agentfee.idAgentFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdAgentFee() {
        return idAgentFee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column agentfee.idAgentFee
     *
     * @param idAgentFee the value for agentfee.idAgentFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdAgentFee(Integer idAgentFee) {
        this.idAgentFee = idAgentFee;
    }
}
