package com.wings.persistence;


public class Authority extends AuthorityKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column authority.description
     *
     * @abatorgenerated Wed May 30 02:05:46 ICT 2007
     */
    private String description;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column authority.description
     *
     * @return the value of authority.description
     *
     * @abatorgenerated Wed May 30 02:05:46 ICT 2007
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column authority.description
     *
     * @param description the value for authority.description
     *
     * @abatorgenerated Wed May 30 02:05:46 ICT 2007
     */
    public void setDescription(String description) {
        if (description != null) {
            description = description.trim();
        }
        this.description = description;
    }
}
