package com.wings.persistence;


public class AuthorityKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column authority.authorityId
     *
     * @abatorgenerated Sat May 26 14:21:48 ICT 2007
     */
    private String authorityId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column authority.authorityId
     *
     * @return the value of authority.authorityId
     *
     * @abatorgenerated Sat May 26 14:21:48 ICT 2007
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column authority.authorityId
     *
     * @param authorityId the value for authority.authorityId
     *
     * @abatorgenerated Sat May 26 14:21:48 ICT 2007
     */
    public void setAuthorityId(String authorityId) {
        if (authorityId != null) {
            authorityId = authorityId.trim();
        }
        this.authorityId = authorityId;
    }
}
