package com.wings.persistence;


public class BatchExample extends Batch {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    private int noBatch_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    private int description_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public int getNoBatch_Indicator() {
        return noBatch_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public void setNoBatch_Indicator(int noBatch_Indicator) {
        this.noBatch_Indicator = noBatch_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public int getDescription_Indicator() {
        return description_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table batch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public void setDescription_Indicator(int description_Indicator) {
        this.description_Indicator = description_Indicator;
    }
}
