package com.wings.persistence;


public class BatchKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column batch.noBatch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    private String noBatch;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column batch.noBatch
     *
     * @return the value of batch.noBatch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public String getNoBatch() {
        return noBatch;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column batch.noBatch
     *
     * @param noBatch the value for batch.noBatch
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public void setNoBatch(String noBatch) {
        if (noBatch != null) {
            noBatch = noBatch.trim();
        }
        this.noBatch = noBatch;
    }
}
