package com.wings.persistence;


public class Batch extends BatchKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column batch.description
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    private String description;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column batch.description
     *
     * @return the value of batch.description
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column batch.description
     *
     * @param description the value for batch.description
     *
     * @abatorgenerated Wed Jul 09 20:47:46 ICT 2008
     */
    public void setDescription(String description) {
        if (description != null) {
            description = description.trim();
        }
        this.description = description;
    }
}
