package com.wings.persistence;


public class Billingshipper extends BillingshipperKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column billingshipper.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idJobSheet;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column billingshipper.idShipperFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idShipperFee;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column billingshipper.charge
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Double charge;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column billingshipper.kurs
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String kurs;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column billingshipper.idJobSheet
     *
     * @return the value of billingshipper.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    
    private String description;
    private Double kursValue;
    private String descriptionInvoice;
    private Double oriKurs;
    private Double oriWeight;
    private Integer isTax;
    private Integer isVat;
    private Double totalTax;
    private Double totalVat;
    private Integer isTax2;
    private Double totalTax2;
    
    public Integer getIdJobSheet() {
        return idJobSheet;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column billingshipper.idJobSheet
     *
     * @param idJobSheet the value for billingshipper.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdJobSheet(Integer idJobSheet) {
        this.idJobSheet = idJobSheet;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column billingshipper.idShipperFee
     *
     * @return the value of billingshipper.idShipperFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdShipperFee() {
        return idShipperFee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column billingshipper.idShipperFee
     *
     * @param idShipperFee the value for billingshipper.idShipperFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdShipperFee(Integer idShipperFee) {
        this.idShipperFee = idShipperFee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column billingshipper.charge
     *
     * @return the value of billingshipper.charge
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Double getCharge() {
        return charge;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column billingshipper.charge
     *
     * @param charge the value for billingshipper.charge
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setCharge(Double charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column billingshipper.kurs
     *
     * @return the value of billingshipper.kurs
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getKurs() {
        return kurs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column billingshipper.kurs
     *
     * @param kurs the value for billingshipper.kurs
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setKurs(String kurs) {
        if (kurs != null) {
            kurs = kurs.trim();
        }
        this.kurs = kurs;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getKursValue() {
        return kursValue;
    }

    public void setKursValue(Double kursValue) {
        this.kursValue = kursValue;
    }

    public String getDescriptionInvoice() {
        return descriptionInvoice;
    }

    public void setDescriptionInvoice(String descriptionInvoice) {
        this.descriptionInvoice = descriptionInvoice;
    }

    public Double getOriKurs() {
        return oriKurs;
    }

    public void setOriKurs(Double oriKurs) {
        this.oriKurs = oriKurs;
    }

    public Double getOriWeight() {
        return oriWeight;
    }

    public void setOriWeight(Double oriWeight) {
        this.oriWeight = oriWeight;
    }

    /**
     * @return the isTax
     */
    public Integer getIsTax() {
        return isTax;
    }

    /**
     * @param isTax the isTax to set
     */
    public void setIsTax(Integer isTax) {
        this.isTax = isTax;
    }

    /**
     * @return the isVat
     */
    public Integer getIsVat() {
        return isVat;
    }

    /**
     * @param isVat the isVat to set
     */
    public void setIsVat(Integer isVat) {
        this.isVat = isVat;
    }

    /**
     * @return the totalTax
     */
    public Double getTotalTax() {
        return totalTax;
    }

    /**
     * @param totalTax the totalTax to set
     */
    public void setTotalTax(Double totalTax) {
        this.totalTax = totalTax;
    }

    /**
     * @return the totalVat
     */
    public Double getTotalVat() {
        return totalVat;
    }

    /**
     * @param totalVat the totalVat to set
     */
    public void setTotalVat(Double totalVat) {
        this.totalVat = totalVat;
    }

    /**
     * @return the isTax2
     */
    public Integer getIsTax2() {
        return isTax2;
    }

    /**
     * @param isTax2 the isTax2 to set
     */
    public void setIsTax2(Integer isTax2) {
        this.isTax2 = isTax2;
    }

    /**
     * @return the totalTax2
     */
    public Double getTotalTax2() {
        return totalTax2;
    }

    /**
     * @param totalTax2 the totalTax2 to set
     */
    public void setTotalTax2(Double totalTax2) {
        this.totalTax2 = totalTax2;
    }

   
}
