package com.wings.persistence;


public class BillingshipperKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column billingshipper.idbillingShipper
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idbillingShipper;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column billingshipper.idbillingShipper
     *
     * @return the value of billingshipper.idbillingShipper
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdbillingShipper() {
        return idbillingShipper;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column billingshipper.idbillingShipper
     *
     * @param idbillingShipper the value for billingshipper.idbillingShipper
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdbillingShipper(Integer idbillingShipper) {
        this.idbillingShipper = idbillingShipper;
    }
}
