package com.wings.persistence;


public class BillingagentKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column billingagent.idbillingAgent
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idbillingAgent;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column billingagent.idbillingAgent
     *
     * @return the value of billingagent.idbillingAgent
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdbillingAgent() {
        return idbillingAgent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column billingagent.idbillingAgent
     *
     * @param idbillingAgent the value for billingagent.idbillingAgent
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdbillingAgent(Integer idbillingAgent) {
        this.idbillingAgent = idbillingAgent;
    }
}
