package com.wings.persistence;

import java.util.Date;

public class Cashonhand {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cashonhand.idCashOnHand
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    private Integer idCashOnHand;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cashonhand.idPerkiraan
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    private Integer idAccount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cashonhand.type
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    private String type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cashonhand.description
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cashonhand.amtIDR
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    private Double amtIDR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cashonhand.amtUSD
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    private Double amtUSD;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cashonhand.amt2USD
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    private Double amt2USD;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cashonhand.amt2IDR
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    private Double amt2IDR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cashonhand.remark
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cashonhand.transDate
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    private Date transDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cashonhand.idCashOnHand
     *
     * @return the value of cashonhand.idCashOnHand
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public Integer getIdCashOnHand() {
        return idCashOnHand;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cashonhand.idCashOnHand
     *
     * @param idCashOnHand the value for cashonhand.idCashOnHand
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public void setIdCashOnHand(Integer idCashOnHand) {
        this.idCashOnHand = idCashOnHand;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cashonhand.type
     *
     * @return the value of cashonhand.type
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cashonhand.type
     *
     * @param type the value for cashonhand.type
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cashonhand.description
     *
     * @return the value of cashonhand.description
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cashonhand.description
     *
     * @param description the value for cashonhand.description
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cashonhand.amtIDR
     *
     * @return the value of cashonhand.amtIDR
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public Double getAmtIDR() {
        return amtIDR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cashonhand.amtIDR
     *
     * @param amtIDR the value for cashonhand.amtIDR
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public void setAmtIDR(Double amtIDR) {
        this.amtIDR = amtIDR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cashonhand.amtUSD
     *
     * @return the value of cashonhand.amtUSD
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public Double getAmtUSD() {
        return amtUSD;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cashonhand.amtUSD
     *
     * @param amtUSD the value for cashonhand.amtUSD
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public void setAmtUSD(Double amtUSD) {
        this.amtUSD = amtUSD;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cashonhand.amt2USD
     *
     * @return the value of cashonhand.amt2USD
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public Double getAmt2USD() {
        return amt2USD;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cashonhand.amt2USD
     *
     * @param amt2USD the value for cashonhand.amt2USD
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public void setAmt2USD(Double amt2USD) {
        this.amt2USD = amt2USD;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cashonhand.amt2IDR
     *
     * @return the value of cashonhand.amt2IDR
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public Double getAmt2IDR() {
        return amt2IDR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cashonhand.amt2IDR
     *
     * @param amt2IDR the value for cashonhand.amt2IDR
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public void setAmt2IDR(Double amt2IDR) {
        this.amt2IDR = amt2IDR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cashonhand.remark
     *
     * @return the value of cashonhand.remark
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cashonhand.remark
     *
     * @param remark the value for cashonhand.remark
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cashonhand.transDate
     *
     * @return the value of cashonhand.transDate
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public Date getTransDate() {
        return transDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cashonhand.transDate
     *
     * @param transDate the value for cashonhand.transDate
     *
     * @ibatorgenerated Thu Oct 29 23:53:53 ICT 2009
     */
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }

    public Integer getIdAccount() {
        return idAccount;
    }

    public void setIdAccount(Integer idAccount) {
        this.idAccount = idAccount;
    }
}