package com.wings.persistence;


public class Consignee extends ConsigneeKey {

    private String name;
    private String description;
    private String description2;
    private String contactPerson;
    private String telp;
    private String fax;
    private String email;
    private String address1;
    private String address2;
    private String postalCode;
    private String city;
    private String region;
    private String npwp;
    private String nppkp;
    private String idAccountIDR;
    private String idAccountUSD;
    
    public Consignee() {
        name = "";
        description = "";
        description2 = "";
        contactPerson = "";
        telp = "";
        fax = "";
        email = "";
        address1 = "";
        address2 = "";
        postalCode = "";
        city = "";
        region = "";
        npwp = "";
        nppkp = "";
        idAccountIDR = "";
        idAccountUSD = "";
    }
    
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.name
     *
     * @param name the value for consignee.name
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setName(String name) {
        if (name != null) {
            name = name.trim();
        }
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column consignee.description
     *
     * @return the value of consignee.description
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.description
     *
     * @param description the value for consignee.description
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setDescription(String description) {
        if (description != null) {
            description = description.trim();
        }
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column consignee.contactPerson
     *
     * @return the value of consignee.contactPerson
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.contactPerson
     *
     * @param contactPerson the value for consignee.contactPerson
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setContactPerson(String contactPerson) {
        if (contactPerson != null) {
            contactPerson = contactPerson.trim();
        }
        this.contactPerson = contactPerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column consignee.telp
     *
     * @return the value of consignee.telp
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getTelp() {
        return telp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.telp
     *
     * @param telp the value for consignee.telp
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setTelp(String telp) {
        if (telp != null) {
            telp = telp.trim();
        }
        this.telp = telp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column consignee.fax
     *
     * @return the value of consignee.fax
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.fax
     *
     * @param fax the value for consignee.fax
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setFax(String fax) {
        if (fax != null) {
            fax = fax.trim();
        }
        this.fax = fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column consignee.email
     *
     * @return the value of consignee.email
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.email
     *
     * @param email the value for consignee.email
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setEmail(String email) {
        if (email != null) {
            email = email.trim();
        }
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column consignee.address1
     *
     * @return the value of consignee.address1
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.address1
     *
     * @param address1 the value for consignee.address1
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setAddress1(String address1) {
        if (address1 != null) {
            address1 = address1.trim();
        }
        this.address1 = address1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column consignee.address2
     *
     * @return the value of consignee.address2
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.address2
     *
     * @param address2 the value for consignee.address2
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setAddress2(String address2) {
        if (address2 != null) {
            address2 = address2.trim();
        }
        this.address2 = address2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column consignee.postalCode
     *
     * @return the value of consignee.postalCode
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.postalCode
     *
     * @param postalCode the value for consignee.postalCode
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setPostalCode(String postalCode) {
        if (postalCode != null) {
            postalCode = postalCode.trim();
        }
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column consignee.city
     *
     * @return the value of consignee.city
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.city
     *
     * @param city the value for consignee.city
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setCity(String city) {
        if (city != null) {
            city = city.trim();
        }
        this.city = city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column consignee.region
     *
     * @return the value of consignee.region
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.region
     *
     * @param region the value for consignee.region
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setRegion(String region) {
        if (region != null) {
            region = region.trim();
        }
        this.region = region;
    }

    public String getNpwp() {
        return npwp;
    }

    public void setNpwp(String npwp) {
        this.npwp = npwp;
    }

    public String getNppkp() {
        return nppkp;
    }

    public void setNppkp(String nppkp) {
        this.nppkp = nppkp;
    }
   
    public String getIdAccountIDR() {
        return idAccountIDR;
    }

    public void setIdAccountIDR(String idAccountIDR) {
        this.idAccountIDR = idAccountIDR;
    }

    public String getIdAccountUSD() {
        return idAccountUSD;
    }

    public void setIdAccountUSD(String idAccountUSD) {
        this.idAccountUSD = idAccountUSD;
    }

    /**
     * @return the description2
     */
    public String getDescription2() {
        return description2;
    }

    /**
     * @param description2 the description2 to set
     */
    public void setDescription2(String description2) {
        this.description2 = description2;
    }
}
