package com.wings.persistence;


public class ConsigneeKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column consignee.idConsignee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String idConsignee;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column consignee.idConsignee
     *
     * @return the value of consignee.idConsignee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getIdConsignee() {
        return idConsignee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column consignee.idConsignee
     *
     * @param idConsignee the value for consignee.idConsignee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdConsignee(String idConsignee) {
        if (idConsignee != null) {
            idConsignee = idConsignee.trim();
        }
        this.idConsignee = idConsignee;
    }
}
