package com.wings.persistence;


public class DebitKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column debit.idDebit
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idDebit;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column debit.idDebit
     *
     * @return the value of debit.idDebit
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdDebit() {
        return idDebit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column debit.idDebit
     *
     * @param idDebit the value for debit.idDebit
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdDebit(Integer idDebit) {
        this.idDebit = idDebit;
    }
}
