package com.wings.persistence;


public class DebitkreditExample extends Debitkredit {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private int idDebitKredit_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private int idDebit_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private int value_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private int kurs_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private int kreditDate_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private int number_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public int getIdDebitKredit_Indicator() {
        return idDebitKredit_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setIdDebitKredit_Indicator(int idDebitKredit_Indicator) {
        this.idDebitKredit_Indicator = idDebitKredit_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public int getIdDebit_Indicator() {
        return idDebit_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setIdDebit_Indicator(int idDebit_Indicator) {
        this.idDebit_Indicator = idDebit_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public int getValue_Indicator() {
        return value_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setValue_Indicator(int value_Indicator) {
        this.value_Indicator = value_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public int getKurs_Indicator() {
        return kurs_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setKurs_Indicator(int kurs_Indicator) {
        this.kurs_Indicator = kurs_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public int getKreditDate_Indicator() {
        return kreditDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setKreditDate_Indicator(int kreditDate_Indicator) {
        this.kreditDate_Indicator = kreditDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public int getNumber_Indicator() {
        return number_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table debitkredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setNumber_Indicator(int number_Indicator) {
        this.number_Indicator = number_Indicator;
    }
}
