package com.wings.persistence;


public class DebitkreditKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column debitkredit.idDebitKredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private Integer idDebitKredit;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column debitkredit.idDebitKredit
     *
     * @return the value of debitkredit.idDebitKredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public Integer getIdDebitKredit() {
        return idDebitKredit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column debitkredit.idDebitKredit
     *
     * @param idDebitKredit the value for debitkredit.idDebitKredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setIdDebitKredit(Integer idDebitKredit) {
        this.idDebitKredit = idDebitKredit;
    }
}
