package com.wings.persistence;


public class DestinationKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column destination.idDestination
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    private String idDestination;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column destination.idDestination
     *
     * @return the value of destination.idDestination
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getIdDestination() {
        return idDestination;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column destination.idDestination
     *
     * @param idDestination the value for destination.idDestination
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setIdDestination(String idDestination) {
        if (idDestination != null) {
            idDestination = idDestination.trim();
        }
        this.idDestination = idDestination;
    }
}
