package com.wings.persistence;


public class Destination extends DestinationKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column destination.name
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    private String name;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column destination.name
     *
     * @return the value of destination.name
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column destination.name
     *
     * @param name the value for destination.name
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setName(String name) {
        if (name != null) {
            name = name.trim();
        }
        this.name = name;
    }
}
