package com.wings.persistence;


public class Expensesagent extends ExpensesagentKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column expensesagent.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idJobSheet;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column expensesagent.idAgentFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idAgentFee;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column expensesagent.charge
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Double charge;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column expensesagent.kurs
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String kurs;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column expensesagent.idJobSheet
     *
     * @return the value of expensesagent.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String description;
    private Double kursValue;
    private String descriptionInvoice;
    private Double oriKurs;
    private Double oriWeight;
    private Integer isTax;
    private Integer isVat;
    private Double totalTax;
    private Double totalVat;
    public Integer getIdJobSheet() {
        return idJobSheet;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column expensesagent.idJobSheet
     *
     * @param idJobSheet the value for expensesagent.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdJobSheet(Integer idJobSheet) {
        this.idJobSheet = idJobSheet;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column expensesagent.idAgentFee
     *
     * @return the value of expensesagent.idAgentFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdAgentFee() {
        return idAgentFee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column expensesagent.idAgentFee
     *
     * @param idAgentFee the value for expensesagent.idAgentFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdAgentFee(Integer idAgentFee) {
        this.idAgentFee = idAgentFee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column expensesagent.charge
     *
     * @return the value of expensesagent.charge
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Double getCharge() {
        return charge;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column expensesagent.charge
     *
     * @param charge the value for expensesagent.charge
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setCharge(Double charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column expensesagent.kurs
     *
     * @return the value of expensesagent.kurs
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getKurs() {
        return kurs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column expensesagent.kurs
     *
     * @param kurs the value for expensesagent.kurs
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setKurs(String kurs) {
        if (kurs != null) {
            kurs = kurs.trim();
        }
        this.kurs = kurs;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getKursValue() {
        return kursValue;
    }

    public void setKursValue(Double kursValue) {
        this.kursValue = kursValue;
    }

    public String getDescriptionInvoice() {
        return descriptionInvoice;
    }

    public void setDescriptionInvoice(String descriptionInvoice) {
        this.descriptionInvoice = descriptionInvoice;
    }

    public Double getOriKurs() {
        return oriKurs;
    }

    public void setOriKurs(Double oriKurs) {
        this.oriKurs = oriKurs;
    }

    public Double getOriWeight() {
        return oriWeight;
    }

    public void setOriWeight(Double oriWeight) {
        this.oriWeight = oriWeight;
    }

    /**
     * @return the isTax
     */
    public Integer getIsTax() {
        return isTax;
    }

    /**
     * @param isTax the isTax to set
     */
    public void setIsTax(Integer isTax) {
        this.isTax = isTax;
    }

    /**
     * @return the isVat
     */
    public Integer getIsVat() {
        return isVat;
    }

    /**
     * @param isVat the isVat to set
     */
    public void setIsVat(Integer isVat) {
        this.isVat = isVat;
    }

    /**
     * @return the totalTax
     */
    public Double getTotalTax() {
        return totalTax;
    }

    /**
     * @param totalTax the totalTax to set
     */
    public void setTotalTax(Double totalTax) {
        this.totalTax = totalTax;
    }

    /**
     * @return the totalVat
     */
    public Double getTotalVat() {
        return totalVat;
    }

    /**
     * @param totalVat the totalVat to set
     */
    public void setTotalVat(Double totalVat) {
        this.totalVat = totalVat;
    }
}
