package com.wings.persistence;


public class ExpensesshipperKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column expensesshipper.idExpensesShipper
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idExpensesShipper;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column expensesshipper.idExpensesShipper
     *
     * @return the value of expensesshipper.idExpensesShipper
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdExpensesShipper() {
        return idExpensesShipper;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column expensesshipper.idExpensesShipper
     *
     * @param idExpensesShipper the value for expensesshipper.idExpensesShipper
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdExpensesShipper(Integer idExpensesShipper) {
        this.idExpensesShipper = idExpensesShipper;
    }
}
