package com.wings.persistence;


public class ExpensesagentKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column expensesagent.idExpensesAgent
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idExpensesAgent;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column expensesagent.idExpensesAgent
     *
     * @return the value of expensesagent.idExpensesAgent
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdExpensesAgent() {
        return idExpensesAgent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column expensesagent.idExpensesAgent
     *
     * @param idExpensesAgent the value for expensesagent.idExpensesAgent
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdExpensesAgent(Integer idExpensesAgent) {
        this.idExpensesAgent = idExpensesAgent;
    }
}
