package com.wings.persistence;


public class IncomeKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column income.idIncome
     *
     * @abatorgenerated Mon Jun 02 11:40:19 ICT 2008
     */
    private Integer idIncome;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column income.idIncome
     *
     * @return the value of income.idIncome
     *
     * @abatorgenerated Mon Jun 02 11:40:19 ICT 2008
     */
    public Integer getIdIncome() {
        return idIncome;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column income.idIncome
     *
     * @param idIncome the value for income.idIncome
     *
     * @abatorgenerated Mon Jun 02 11:40:19 ICT 2008
     */
    public void setIdIncome(Integer idIncome) {
        this.idIncome = idIncome;
    }
}
