package com.wings.persistence;


public class InvoicekreditExample extends Invoicekredit {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private int idInvoiceKredit_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private int idInvoice_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private int value_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private int kreditDate_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private int number_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public int getIdInvoiceKredit_Indicator() {
        return idInvoiceKredit_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setIdInvoiceKredit_Indicator(int idInvoiceKredit_Indicator) {
        this.idInvoiceKredit_Indicator = idInvoiceKredit_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public int getIdInvoice_Indicator() {
        return idInvoice_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setIdInvoice_Indicator(int idInvoice_Indicator) {
        this.idInvoice_Indicator = idInvoice_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public int getValue_Indicator() {
        return value_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setValue_Indicator(int value_Indicator) {
        this.value_Indicator = value_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public int getKreditDate_Indicator() {
        return kreditDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setKreditDate_Indicator(int kreditDate_Indicator) {
        this.kreditDate_Indicator = kreditDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public int getNumber_Indicator() {
        return number_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table invoicekredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setNumber_Indicator(int number_Indicator) {
        this.number_Indicator = number_Indicator;
    }
}
