package com.wings.persistence;

import java.util.Date;

public class Invoicekredit extends InvoicekreditKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column invoicekredit.idInvoice
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private Integer idInvoice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column invoicekredit.value
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private Double value;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column invoicekredit.kreditDate
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private Date kreditDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column invoicekredit.number
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private Integer number;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column invoicekredit.idInvoice
     *
     * @return the value of invoicekredit.idInvoice
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    
    private String kurs;
    
    public Integer getIdInvoice() {
        return idInvoice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column invoicekredit.idInvoice
     *
     * @param idInvoice the value for invoicekredit.idInvoice
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setIdInvoice(Integer idInvoice) {
        this.idInvoice = idInvoice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column invoicekredit.value
     *
     * @return the value of invoicekredit.value
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column invoicekredit.value
     *
     * @param value the value for invoicekredit.value
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column invoicekredit.kreditDate
     *
     * @return the value of invoicekredit.kreditDate
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public Date getKreditDate() {
        return kreditDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column invoicekredit.kreditDate
     *
     * @param kreditDate the value for invoicekredit.kreditDate
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setKreditDate(Date kreditDate) {
        this.kreditDate = kreditDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column invoicekredit.number
     *
     * @return the value of invoicekredit.number
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column invoicekredit.number
     *
     * @param number the value for invoicekredit.number
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    public String getKurs() {
        return kurs;
    }

    public void setKurs(String kurs) {
        this.kurs = kurs;
    }
}
