package com.wings.persistence;


public class InvoicekreditKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column invoicekredit.idInvoiceKredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    private Integer idInvoiceKredit;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column invoicekredit.idInvoiceKredit
     *
     * @return the value of invoicekredit.idInvoiceKredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public Integer getIdInvoiceKredit() {
        return idInvoiceKredit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column invoicekredit.idInvoiceKredit
     *
     * @param idInvoiceKredit the value for invoicekredit.idInvoiceKredit
     *
     * @abatorgenerated Tue Jun 03 22:44:21 ICT 2008
     */
    public void setIdInvoiceKredit(Integer idInvoiceKredit) {
        this.idInvoiceKredit = idInvoiceKredit;
    }
}
