package com.wings.persistence;


public class InvoiceKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column invoice.idInvoice
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idInvoice;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column invoice.idInvoice
     *
     * @return the value of invoice.idInvoice
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdInvoice() {
        return idInvoice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column invoice.idInvoice
     *
     * @param idInvoice the value for invoice.idInvoice
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdInvoice(Integer idInvoice) {
        this.idInvoice = idInvoice;
    }
}
