package com.wings.persistence;


public class JobsheetsoKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetso.idJobSheetSO
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idJobSheetSO;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.idJobSheetSO
     *
     * @return the value of jobsheetso.idJobSheetSO
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdJobSheetSO() {
        return idJobSheetSO;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.idJobSheetSO
     *
     * @param idJobSheetSO the value for jobsheetso.idJobSheetSO
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdJobSheetSO(Integer idJobSheetSO) {
        this.idJobSheetSO = idJobSheetSO;
    }
}
