package com.wings.persistence;


public class JobsheetsiKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetsi.idJobSheetSI
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idJobSheetSI;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetsi.idJobSheetSI
     *
     * @return the value of jobsheetsi.idJobSheetSI
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdJobSheetSI() {
        return idJobSheetSI;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetsi.idJobSheetSI
     *
     * @param idJobSheetSI the value for jobsheetsi.idJobSheetSI
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdJobSheetSI(Integer idJobSheetSI) {
        this.idJobSheetSI = idJobSheetSI;
    }
}
