package com.wings.persistence;


public class JobsheetKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheet.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idJobSheet;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.idJobSheet
     *
     * @return the value of jobsheet.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdJobSheet() {
        return idJobSheet;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.idJobSheet
     *
     * @param idJobSheet the value for jobsheet.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdJobSheet(Integer idJobSheet) {
        this.idJobSheet = idJobSheet;
    }
}
