package com.wings.persistence;


public class Jobsheetao extends JobsheetaoKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idJobSheet;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.dnNo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String dnNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.destination
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String destination;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.flights
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String flights;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.cntFlight
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String cntFlight;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.freightTerm
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String freightTerm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.bookingTo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String bookingTo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.operationStaff
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String operationStaff;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.telpColoader
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String telpColoader;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.faxColoader
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String faxColoader;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.picColoader
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String picColoader;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.mawb
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String mawb;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.hawb
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String hawb;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.epte
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String epte;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.pibNo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String pibNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.dimention
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String dimention;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.pickupCargo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String pickupCargo;

    private String commodity;
    
    private String billTo;
    
    private String cnNo;
    
    private String billToDebit;
    private String remark;
    private String jaminan;
    public Integer getIdJobSheet() {
        return idJobSheet;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.idJobSheet
     *
     * @param idJobSheet the value for jobsheetao.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdJobSheet(Integer idJobSheet) {
        this.idJobSheet = idJobSheet;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.dnNo
     *
     * @return the value of jobsheetao.dnNo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getDnNo() {
        return dnNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.dnNo
     *
     * @param dnNo the value for jobsheetao.dnNo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setDnNo(String dnNo) {
        if (dnNo != null) {
            dnNo = dnNo.trim();
        }
        this.dnNo = dnNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.destination
     *
     * @return the value of jobsheetao.destination
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.destination
     *
     * @param destination the value for jobsheetao.destination
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setDestination(String destination) {
        if (destination != null) {
            destination = destination.trim();
        }
        this.destination = destination;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.flights
     *
     * @return the value of jobsheetao.flights
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getFlights() {
        return flights;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.flights
     *
     * @param flights the value for jobsheetao.flights
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setFlights(String flights) {
        if (flights != null) {
            flights = flights.trim();
        }
        this.flights = flights;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.cntFlight
     *
     * @return the value of jobsheetao.cntFlight
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getCntFlight() {
        return cntFlight;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.cntFlight
     *
     * @param cntFlight the value for jobsheetao.cntFlight
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setCntFlight(String cntFlight) {
        if (cntFlight != null) {
            cntFlight = cntFlight.trim();
        }
        this.cntFlight = cntFlight;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.freightTerm
     *
     * @return the value of jobsheetao.freightTerm
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getFreightTerm() {
        return freightTerm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.freightTerm
     *
     * @param freightTerm the value for jobsheetao.freightTerm
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setFreightTerm(String freightTerm) {
        if (freightTerm != null) {
            freightTerm = freightTerm.trim();
        }
        this.freightTerm = freightTerm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.bookingTo
     *
     * @return the value of jobsheetao.bookingTo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getBookingTo() {
        return bookingTo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.bookingTo
     *
     * @param bookingTo the value for jobsheetao.bookingTo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setBookingTo(String bookingTo) {
        if (bookingTo != null) {
            bookingTo = bookingTo.trim();
        }
        this.bookingTo = bookingTo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.operationStaff
     *
     * @return the value of jobsheetao.operationStaff
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getOperationStaff() {
        return operationStaff;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.operationStaff
     *
     * @param operationStaff the value for jobsheetao.operationStaff
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setOperationStaff(String operationStaff) {
        if (operationStaff != null) {
            operationStaff = operationStaff.trim();
        }
        this.operationStaff = operationStaff;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.telpColoader
     *
     * @return the value of jobsheetao.telpColoader
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getTelpColoader() {
        return telpColoader;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.telpColoader
     *
     * @param telpColoader the value for jobsheetao.telpColoader
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setTelpColoader(String telpColoader) {
        if (telpColoader != null) {
            telpColoader = telpColoader.trim();
        }
        this.telpColoader = telpColoader;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.faxColoader
     *
     * @return the value of jobsheetao.faxColoader
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getFaxColoader() {
        return faxColoader;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.faxColoader
     *
     * @param faxColoader the value for jobsheetao.faxColoader
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setFaxColoader(String faxColoader) {
        if (faxColoader != null) {
            faxColoader = faxColoader.trim();
        }
        this.faxColoader = faxColoader;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.picColoader
     *
     * @return the value of jobsheetao.picColoader
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getPicColoader() {
        return picColoader;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.picColoader
     *
     * @param picColoader the value for jobsheetao.picColoader
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setPicColoader(String picColoader) {
        if (picColoader != null) {
            picColoader = picColoader.trim();
        }
        this.picColoader = picColoader;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.mawb
     *
     * @return the value of jobsheetao.mawb
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getMawb() {
        return mawb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.mawb
     *
     * @param mawb the value for jobsheetao.mawb
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setMawb(String mawb) {
        if (mawb != null) {
            mawb = mawb.trim();
        }
        this.mawb = mawb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.hawb
     *
     * @return the value of jobsheetao.hawb
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getHawb() {
        return hawb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.hawb
     *
     * @param hawb the value for jobsheetao.hawb
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setHawb(String hawb) {
        if (hawb != null) {
            hawb = hawb.trim();
        }
        this.hawb = hawb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.epte
     *
     * @return the value of jobsheetao.epte
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getEpte() {
        return epte;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.epte
     *
     * @param epte the value for jobsheetao.epte
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setEpte(String epte) {
        if (epte != null) {
            epte = epte.trim();
        }
        this.epte = epte;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.pibNo
     *
     * @return the value of jobsheetao.pibNo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getPibNo() {
        return pibNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.pibNo
     *
     * @param pibNo the value for jobsheetao.pibNo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setPibNo(String pibNo) {
        if (pibNo != null) {
            pibNo = pibNo.trim();
        }
        this.pibNo = pibNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.dimention
     *
     * @return the value of jobsheetao.dimention
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getDimention() {
        return dimention;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.dimention
     *
     * @param dimention the value for jobsheetao.dimention
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setDimention(String dimention) {
        if (dimention != null) {
            dimention = dimention.trim();
        }
        this.dimention = dimention;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.pickupCargo
     *
     * @return the value of jobsheetao.pickupCargo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getPickupCargo() {
        return pickupCargo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.pickupCargo
     *
     * @param pickupCargo the value for jobsheetao.pickupCargo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setPickupCargo(String pickupCargo) {
        if (pickupCargo != null) {
            pickupCargo = pickupCargo.trim();
        }
        this.pickupCargo = pickupCargo;
    }

    public String getCommodity() {
        return commodity;
    }

    public void setCommodity(String commodity) {
        this.commodity = commodity;
    }

    public String getBillTo() {
        return billTo;
    }

    public void setBillTo(String billTo) {
        this.billTo = billTo;
    }

    public String getCnNo() {
        return cnNo;
    }

    public void setCnNo(String cnNo) {
        this.cnNo = cnNo;
    }

    public String getBillToDebit() {
        return billToDebit;
    }

    public void setBillToDebit(String billToDebit) {
        this.billToDebit = billToDebit;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the jaminan
     */
    public String getJaminan() {
        return jaminan;
    }

    /**
     * @param jaminan the jaminan to set
     */
    public void setJaminan(String jaminan) {
        this.jaminan = jaminan;
    }
}
