package com.wings.persistence;

import java.util.Date;

public class Jobsheetso extends JobsheetsoKey {

    
    private Integer idJobSheet;

    
    private String shippingLine;

    private String shippingLineName;

    private String feederVessel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetso.mVessel
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String mvessel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetso.termMBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String termMBL;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetso.termHBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String termHBL;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetso.origin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String origin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetso.destination
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String destination;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetso.ETDOrigin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Date ETDOrigin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetso.ETADestination
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Date ETADestination;
    
    private Date sinDate; 

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetso.MBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String MBL;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetso.trucking
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String trucking;

    private String commodity;
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.idJobSheet
     *
     * @return the value of jobsheetso.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String billTo;

    private String cnNo;
    private String dnNo;
    private String billToDebit;
    private String remark;
    private String jaminan;
    public Integer getIdJobSheet() {
        return idJobSheet;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.idJobSheet
     *
     * @param idJobSheet the value for jobsheetso.idJobSheet
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdJobSheet(Integer idJobSheet) {
        this.idJobSheet = idJobSheet;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.shippingLine
     *
     * @return the value of jobsheetso.shippingLine
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getShippingLine() {
        return shippingLine;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.shippingLine
     *
     * @param shippingLine the value for jobsheetso.shippingLine
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setShippingLine(String shippingLine) {
        if (shippingLine != null) {
            shippingLine = shippingLine.trim();
        }
        this.shippingLine = shippingLine;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.feederVessel
     *
     * @return the value of jobsheetso.feederVessel
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getFeederVessel() {
        return feederVessel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.feederVessel
     *
     * @param feederVessel the value for jobsheetso.feederVessel
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setFeederVessel(String feederVessel) {
        if (feederVessel != null) {
            feederVessel = feederVessel.trim();
        }
        this.feederVessel = feederVessel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.mVessel
     *
     * @return the value of jobsheetso.mVessel
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getMvessel() {
        return mvessel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.mVessel
     *
     * @param mVessel the value for jobsheetso.mVessel
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setMvessel(String mvessel) {
        if (mvessel != null) {
            mvessel = mvessel.trim();
        }
        this.mvessel = mvessel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.termMBL
     *
     * @return the value of jobsheetso.termMBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getTermMBL() {
        return termMBL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.termMBL
     *
     * @param termMBL the value for jobsheetso.termMBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setTermMBL(String termMBL) {
        if (termMBL != null) {
            termMBL = termMBL.trim();
        }
        this.termMBL = termMBL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.termHBL
     *
     * @return the value of jobsheetso.termHBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getTermHBL() {
        return termHBL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.termHBL
     *
     * @param termHBL the value for jobsheetso.termHBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setTermHBL(String termHBL) {
        if (termHBL != null) {
            termHBL = termHBL.trim();
        }
        this.termHBL = termHBL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.origin
     *
     * @return the value of jobsheetso.origin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.origin
     *
     * @param origin the value for jobsheetso.origin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setOrigin(String origin) {
        if (origin != null) {
            origin = origin.trim();
        }
        this.origin = origin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.destination
     *
     * @return the value of jobsheetso.destination
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.destination
     *
     * @param destination the value for jobsheetso.destination
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setDestination(String destination) {
        if (destination != null) {
            destination = destination.trim();
        }
        this.destination = destination;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.ETDOrigin
     *
     * @return the value of jobsheetso.ETDOrigin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Date getETDOrigin() {
        return ETDOrigin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.ETDOrigin
     *
     * @param ETDOrigin the value for jobsheetso.ETDOrigin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setETDOrigin(Date ETDOrigin) {
        this.ETDOrigin = ETDOrigin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.ETADestination
     *
     * @return the value of jobsheetso.ETADestination
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Date getETADestination() {
        return ETADestination;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.ETADestination
     *
     * @param ETADestination the value for jobsheetso.ETADestination
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setETADestination(Date ETADestination) {
        this.ETADestination = ETADestination;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.MBL
     *
     * @return the value of jobsheetso.MBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getMBL() {
        return MBL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.MBL
     *
     * @param MBL the value for jobsheetso.MBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setMBL(String MBL) {
        if (MBL != null) {
            MBL = MBL.trim();
        }
        this.MBL = MBL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetso.trucking
     *
     * @return the value of jobsheetso.trucking
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getTrucking() {
        return trucking;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetso.trucking
     *
     * @param trucking the value for jobsheetso.trucking
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setTrucking(String trucking) {
        if (trucking != null) {
            trucking = trucking.trim();
        }
        this.trucking = trucking;
    }

    public String getCommodity() {
        return commodity;
    }

    public void setCommodity(String commodity) {
        this.commodity = commodity;
    }

    public Date getSinDate() {
        return sinDate;
    }

    public void setSinDate(Date sinDate) {
        this.sinDate = sinDate;
    }

    public String getBillTo() {
        return billTo;
    }

    public void setBillTo(String billTo) {
        this.billTo = billTo;
    }

    public String getCnNo() {
        return cnNo;
    }

    public void setCnNo(String cnNo) {
        this.cnNo = cnNo;
    }

    public String getDnNo() {
        return dnNo;
    }

    public void setDnNo(String dnNo) {
        this.dnNo = dnNo;
    }

    public String getBillToDebit() {
        return billToDebit;
    }

    public void setBillToDebit(String billToDebit) {
        this.billToDebit = billToDebit;
    }

    /**
     * @return the shippingLineName
     */
    public String getShippingLineName() {
        return shippingLineName;
    }

    /**
     * @param shippingLineName the shippingLineName to set
     */
    public void setShippingLineName(String shippingLineName) {
        this.shippingLineName = shippingLineName;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the jaminan
     */
    public String getJaminan() {
        return jaminan;
    }

    /**
     * @param jaminan the jaminan to set
     */
    public void setJaminan(String jaminan) {
        this.jaminan = jaminan;
    }
}
