package com.wings.persistence;

import java.util.Date;

public class Jobsheetsi extends JobsheetsiKey {

 
    private Integer idJobSheet;


    private String shippingLine;

    private String shippingLineName;
   
    private String feederVessel;

    
    private String mvessel;

   
    private String termMBL;

    
    private String termHBL;

    
    private String origin;

    
    private Date ETDOrigin;

    
    private Date ETAOrigin;
    
    private Date customDate;
    
    private String POD;

    private String trucking;
    
    private String commodity;

    private String billTo;

    private String cnNo;

    private String dnNo;
    
    private String billToDebit;
    private String remark;
    private String jaminan;
    public Integer getIdJobSheet() {
        return idJobSheet;
    }

    public void setIdJobSheet(Integer idJobSheet) {
        this.idJobSheet = idJobSheet;
    }

    public String getShippingLine() {
        return shippingLine;
    }

    public void setShippingLine(String shippingLine) {
        if (shippingLine != null) {
            shippingLine = shippingLine.trim();
        }
        this.shippingLine = shippingLine;
    }

    public String getFeederVessel() {
        return feederVessel;
    }

    public void setFeederVessel(String feederVessel) {
        if (feederVessel != null) {
            feederVessel = feederVessel.trim();
        }
        this.feederVessel = feederVessel;
    }

    
    public String getMvessel() {
        return mvessel;
    }

    
    public void setMvessel(String mvessel) {
        if (mvessel != null) {
            mvessel = mvessel.trim();
        }
        this.mvessel = mvessel;
    }

   public String getTermMBL() {
        return termMBL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetsi.termMBL
     *
     * @param termMBL the value for jobsheetsi.termMBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setTermMBL(String termMBL) {
        if (termMBL != null) {
            termMBL = termMBL.trim();
        }
        this.termMBL = termMBL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetsi.termHBL
     *
     * @return the value of jobsheetsi.termHBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getTermHBL() {
        return termHBL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetsi.termHBL
     *
     * @param termHBL the value for jobsheetsi.termHBL
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setTermHBL(String termHBL) {
        if (termHBL != null) {
            termHBL = termHBL.trim();
        }
        this.termHBL = termHBL;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetsi.origin
     *
     * @return the value of jobsheetsi.origin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetsi.origin
     *
     * @param origin the value for jobsheetsi.origin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setOrigin(String origin) {
        if (origin != null) {
            origin = origin.trim();
        }
        this.origin = origin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetsi.ETDOrigin
     *
     * @return the value of jobsheetsi.ETDOrigin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Date getETDOrigin() {
        return ETDOrigin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetsi.ETDOrigin
     *
     * @param ETDOrigin the value for jobsheetsi.ETDOrigin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setETDOrigin(Date ETDOrigin) {
        this.ETDOrigin = ETDOrigin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetsi.ETAOrigin
     *
     * @return the value of jobsheetsi.ETAOrigin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Date getETAOrigin() {
        return ETAOrigin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetsi.ETAOrigin
     *
     * @param ETAOrigin the value for jobsheetsi.ETAOrigin
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setETAOrigin(Date ETAOrigin) {
        this.ETAOrigin = ETAOrigin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetsi.POD
     *
     * @return the value of jobsheetsi.POD
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getPOD() {
        return POD;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetsi.POD
     *
     * @param POD the value for jobsheetsi.POD
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setPOD(String POD) {
        if (POD != null) {
            POD = POD.trim();
        }
        this.POD = POD;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetsi.trucking
     *
     * @return the value of jobsheetsi.trucking
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getTrucking() {
        return trucking;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetsi.trucking
     *
     * @param trucking the value for jobsheetsi.trucking
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setTrucking(String trucking) {
        if (trucking != null) {
            trucking = trucking.trim();
        }
        this.trucking = trucking;
    }

    public String getCommodity() {
        return commodity;
    }

    public void setCommodity(String commodity) {
        this.commodity = commodity;
    }

    public Date getCustomDate() {
        return customDate;
    }

    public void setCustomDate(Date customDate) {
        this.customDate = customDate;
    }

    public String getBillTo() {
        return billTo;
    }

    public void setBillTo(String billTo) {
        this.billTo = billTo;
    }

    public String getCnNo() {
        return cnNo;
    }

    public void setCnNo(String cnNo) {
        this.cnNo = cnNo;
    }

    public String getDnNo() {
        return dnNo;
    }

    public void setDnNo(String dnNo) {
        this.dnNo = dnNo;
    }

    public String getBillToDebit() {
        return billToDebit;
    }

    public void setBillToDebit(String billToDebit) {
        this.billToDebit = billToDebit;
    }

    /**
     * @return the shippingLineName
     */
    public String getShippingLineName() {
        return shippingLineName;
    }

    /**
     * @param shippingLineName the shippingLineName to set
     */
    public void setShippingLineName(String shippingLineName) {
        this.shippingLineName = shippingLineName;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the jaminan
     */
    public String getJaminan() {
        return jaminan;
    }

    /**
     * @param jaminan the jaminan to set
     */
    public void setJaminan(String jaminan) {
        this.jaminan = jaminan;
    }
}
