package com.wings.persistence;


public class JobsheetaiKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetai.idJobSheetAI
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idJobSheetAI;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetai.idJobSheetAI
     *
     * @return the value of jobsheetai.idJobSheetAI
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdJobSheetAI() {
        return idJobSheetAI;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetai.idJobSheetAI
     *
     * @param idJobSheetAI the value for jobsheetai.idJobSheetAI
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdJobSheetAI(Integer idJobSheetAI) {
        this.idJobSheetAI = idJobSheetAI;
    }
}
