package com.wings.persistence;


public class JobsheetaoKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobsheetao.idJobSheetAO
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idJobSheetAO;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetao.idJobSheetAO
     *
     * @return the value of jobsheetao.idJobSheetAO
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdJobSheetAO() {
        return idJobSheetAO;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetao.idJobSheetAO
     *
     * @param idJobSheetAO the value for jobsheetao.idJobSheetAO
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdJobSheetAO(Integer idJobSheetAO) {
        this.idJobSheetAO = idJobSheetAO;
    }
}
