package com.wings.persistence;

import java.util.Date;

public class Jobsheet extends JobsheetKey {

    
    private String jobNo;

    
    private String invoiceNoUSD;

    
    private String idShipper;

    
    private String idConsignee;

    private String idForwarder;
    
    private String idAgent;

    
    private Double qty;

    
    private Double weight;

    
    private Double volume;

    
    private String qtyDesc;

    
    private String weightDesc;

    
    private String volumeDesc;

    
    private String idJobType;

    
    private Date shippeddate;

    private String remark;

    
    private Double totalBillingIDR;

    
    private Double totalExpensesIDR;

    private Double totalBillingUSD;

    
    private Double totalExpensesUSD;

    
    private String invoiceStatus;

    
    private String debitStatus;

    private String idTransporter;
    
    private Double transportCost;

    private Double transportExp;
    
    private Double refundIDR;
    
    private Double refundUSD;
    
    private String cnNo;
    
    private Double depart;
    
    private String cnKurs;

    private String refundKurs;

    private String debitNo;
    
    private String cmb;
    
    private Double creditNoteIDR;
    
    private Double creditNoteUSD;
    private Double jaminan;
    
    private Integer status;
    
    private Double vatIDR;
    private Double pphIDR;
    private Double vatUSD;
    private Double pphUSD;
    
    private Double dppIDR;
    private Double dppUSD;
    
    private Double dppIDR2;
    private Double vatIDR2;
   
    public String getJobNo() {
        return jobNo;
    }

    
    public void setJobNo(String jobNo) {
        if (jobNo != null) {
            jobNo = jobNo.trim();
        }
        this.jobNo = jobNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.invoiceNoUSD
     *
     * @return the value of jobsheet.invoiceNoUSD
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getInvoiceNoUSD() {
        return invoiceNoUSD;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.invoiceNoUSD
     *
     * @param invoiceNoUSD the value for jobsheet.invoiceNoUSD
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setInvoiceNoUSD(String invoiceNoUSD) {
        if (invoiceNoUSD != null) {
            invoiceNoUSD = invoiceNoUSD.trim();
        }
        this.invoiceNoUSD = invoiceNoUSD;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.idShipper
     *
     * @return the value of jobsheet.idShipper
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getIdShipper() {
        return idShipper;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.idShipper
     *
     * @param idShipper the value for jobsheet.idShipper
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdShipper(String idShipper) {
        if (idShipper != null) {
            idShipper = idShipper.trim();
        }
        this.idShipper = idShipper;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.idConsignee
     *
     * @return the value of jobsheet.idConsignee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getIdConsignee() {
        return idConsignee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.idConsignee
     *
     * @param idConsignee the value for jobsheet.idConsignee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdConsignee(String idConsignee) {
        if (idConsignee != null) {
            idConsignee = idConsignee.trim();
        }
        this.idConsignee = idConsignee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.idAgent
     *
     * @return the value of jobsheet.idAgent
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getIdAgent() {
        return idAgent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.idAgent
     *
     * @param idAgent the value for jobsheet.idAgent
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdAgent(String idAgent) {
        if (idAgent != null) {
            idAgent = idAgent.trim();
        }
        this.idAgent = idAgent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.qty
     *
     * @return the value of jobsheet.qty
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Double getQty() {
        return qty;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.qty
     *
     * @param qty the value for jobsheet.qty
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setQty(Double qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.weight
     *
     * @return the value of jobsheet.weight
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.weight
     *
     * @param weight the value for jobsheet.weight
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.volume
     *
     * @return the value of jobsheet.volume
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.volume
     *
     * @param volume the value for jobsheet.volume
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.qtyDesc
     *
     * @return the value of jobsheet.qtyDesc
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getQtyDesc() {
        return qtyDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.qtyDesc
     *
     * @param qtyDesc the value for jobsheet.qtyDesc
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setQtyDesc(String qtyDesc) {
        if (qtyDesc != null) {
            qtyDesc = qtyDesc.trim();
        }
        this.qtyDesc = qtyDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.weightDesc
     *
     * @return the value of jobsheet.weightDesc
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getWeightDesc() {
        return weightDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.weightDesc
     *
     * @param weightDesc the value for jobsheet.weightDesc
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setWeightDesc(String weightDesc) {
        if (weightDesc != null) {
            weightDesc = weightDesc.trim();
        }
        this.weightDesc = weightDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.volumeDesc
     *
     * @return the value of jobsheet.volumeDesc
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getVolumeDesc() {
        return volumeDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.volumeDesc
     *
     * @param volumeDesc the value for jobsheet.volumeDesc
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setVolumeDesc(String volumeDesc) {
        if (volumeDesc != null) {
            volumeDesc = volumeDesc.trim();
        }
        this.volumeDesc = volumeDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.idJobType
     *
     * @return the value of jobsheet.idJobType
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getIdJobType() {
        return idJobType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.idJobType
     *
     * @param idJobType the value for jobsheet.idJobType
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdJobType(String idJobType) {
        if (idJobType != null) {
            idJobType = idJobType.trim();
        }
        this.idJobType = idJobType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.shippeddate
     *
     * @return the value of jobsheet.shippeddate
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Date getShippeddate() {
        return shippeddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.shippeddate
     *
     * @param shippeddate the value for jobsheet.shippeddate
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setShippeddate(Date shippeddate) {
        this.shippeddate = shippeddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.remark
     *
     * @return the value of jobsheet.remark
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.remark
     *
     * @param remark the value for jobsheet.remark
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setRemark(String remark) {
        if (remark != null) {
            remark = remark.trim();
        }
        this.remark = remark;
    }

   
    public String getInvoiceStatus() {
        return invoiceStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.InvoiceStatus
     *
     * @param InvoiceStatus the value for jobsheet.InvoiceStatus
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setInvoiceStatus(String invoiceStatus) {
        if (invoiceStatus != null) {
            invoiceStatus = invoiceStatus.trim();
        }
        this.invoiceStatus = invoiceStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheet.DebitStatus
     *
     * @return the value of jobsheet.DebitStatus
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getDebitStatus() {
        return debitStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheet.DebitStatus
     *
     * @param DebitStatus the value for jobsheet.DebitStatus
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setDebitStatus(String debitStatus) {
        if (debitStatus != null) {
            debitStatus = debitStatus.trim();
        }
        this.debitStatus = debitStatus;
    }

    public Double getTotalBillingIDR() {
        return totalBillingIDR;
    }

    public void setTotalBillingIDR(Double totalBillingIDR) {
        this.totalBillingIDR = totalBillingIDR;
    }

    public Double getTotalExpensesIDR() {
        return totalExpensesIDR;
    }

    public void setTotalExpensesIDR(Double totalExpensesIDR) {
        this.totalExpensesIDR = totalExpensesIDR;
    }

    public Double getTotalBillingUSD() {
        return totalBillingUSD;
    }

    public void setTotalBillingUSD(Double totalBillingUSD) {
        this.totalBillingUSD = totalBillingUSD;
    }

    public Double getTotalExpensesUSD() {
        return totalExpensesUSD;
    }

    public void setTotalExpensesUSD(Double totalExpensesUSD) {
        this.totalExpensesUSD = totalExpensesUSD;
    }

    public String getIdTransporter() {
        return idTransporter;
    }

    public void setIdTransporter(String idTransporter) {
        this.idTransporter = idTransporter;
    }

    public Double getTransportCost() {
        return transportCost;
    }

    public void setTransportCost(Double transportCost) {
        this.transportCost = transportCost;
    }

    public String getCnNo() {
        return cnNo;
    }

    public void setCnNo(String cnNo) {
        this.cnNo = cnNo;
    }

    public Double getDepart() {
        return depart;
    }

    public void setDepart(Double depart) {
        this.depart = depart;
    }

    public String getCnKurs() {
        return cnKurs;
    }

    public void setCnKurs(String cnKurs) {
        this.cnKurs = cnKurs;
    }

    public String getDebitNo() {
        return debitNo;
    }

    public void setDebitNo(String debitNo) {
        this.debitNo = debitNo;
    }

    public String getCmb() {
        return cmb;
    }

    public void setCmb(String cmb) {
        this.cmb = cmb;
    }

    public Double getRefundIDR() {
        return refundIDR;
    }

    public void setRefundIDR(Double refundIDR) {
        this.refundIDR = refundIDR;
    }

    public Double getRefundUSD() {
        return refundUSD;
    }

    public void setRefundUSD(Double refundUSD) {
        this.refundUSD = refundUSD;
    }

    public Double getCreditNoteIDR() {
        return creditNoteIDR;
    }

    public void setCreditNoteIDR(Double creditNoteIDR) {
        this.creditNoteIDR = creditNoteIDR;
    }

    public Double getCreditNoteUSD() {
        return creditNoteUSD;
    }

    public void setCreditNoteUSD(Double creditNoteUSD) {
        this.creditNoteUSD = creditNoteUSD;
    }

    /**
     * @return the transportExp
     */
    public Double getTransportExp() {
        return transportExp;
    }

    /**
     * @param transportExp the transportExp to set
     */
    public void setTransportExp(Double transportExp) {
        this.transportExp = transportExp;
    }

    /**
     * @return the idForwarder
     */
    public String getIdForwarder() {
        return idForwarder;
    }

    /**
     * @param idForwarder the idForwarder to set
     */
    public void setIdForwarder(String idForwarder) {
        this.idForwarder = idForwarder;
    }

    /**
     * @return the jaminan
     */
    public Double getJaminan() {
        return jaminan;
    }

    /**
     * @param jaminan the jaminan to set
     */
    public void setJaminan(Double jaminan) {
        this.jaminan = jaminan;
    }        
    /**
     * @return the status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * @return the vatIDR
     */
    public Double getVatIDR() {
        return vatIDR;
    }

    /**
     * @param vatIDR the vatIDR to set
     */
    public void setVatIDR(Double vatIDR) {
        this.vatIDR = vatIDR;
    }

    /**
     * @return the pphIDR
     */
    public Double getPphIDR() {
        return pphIDR;
    }

    /**
     * @param pphIDR the pphIDR to set
     */
    public void setPphIDR(Double pphIDR) {
        this.pphIDR = pphIDR;
    }

    /**
     * @return the vatUSD
     */
    public Double getVatUSD() {
        return vatUSD;
    }

    /**
     * @param vatUSD the vatUSD to set
     */
    public void setVatUSD(Double vatUSD) {
        this.vatUSD = vatUSD;
    }

    /**
     * @return the pphUSD
     */
    public Double getPphUSD() {
        return pphUSD;
    }

    /**
     * @param pphUSD the pphUSD to set
     */
    public void setPphUSD(Double pphUSD) {
        this.pphUSD = pphUSD;
    }

    /**
     * @return the dppIDR
     */
    public Double getDppIDR() {
        return dppIDR;
    }

    /**
     * @param dppIDR the dppIDR to set
     */
    public void setDppIDR(Double dppIDR) {
        this.dppIDR = dppIDR;
    }

    /**
     * @return the dppUSD
     */
    public Double getDppUSD() {
        return dppUSD;
    }

    /**
     * @param dppUSD the dppUSD to set
     */
    public void setDppUSD(Double dppUSD) {
        this.dppUSD = dppUSD;
    }

    /**
     * @return the dppIDR2
     */
    public Double getDppIDR2() {
        return dppIDR2;
    }

    /**
     * @param dppIDR2 the dppIDR2 to set
     */
    public void setDppIDR2(Double dppIDR2) {
        this.dppIDR2 = dppIDR2;
    }

    /**
     * @return the vatIDR2
     */
    public Double getVatIDR2() {
        return vatIDR2;
    }

    /**
     * @param vatIDR2 the vatIDR2 to set
     */
    public void setVatIDR2(Double vatIDR2) {
        this.vatIDR2 = vatIDR2;
    }
    
}
