package com.wings.persistence;


public class Jobsheetai extends JobsheetaiKey {

    
    private Integer idJobSheet;

    
    private String dnNo;

    
    private String destination;

    
    private String flights;

    
    private String cntFlight;

    
    private String freightTerm;

    
    private String agentTo;

    
    private String operationStaff;

    
    private String telpColoader;

    
    private String faxColoader;

    
    private String picColoader;

    
    private String mawb;

    
    private String hawb;

    
    private String epte;

    
    private String pibNo;

    
    private String dimention;

    
    private String pickupCargo;

    private String commodity;
    
    private String billTo;

    private String cnNo;
    
    private String billToDebit;
    private String remark;
    private String jaminan;
    
    public Integer getIdJobSheet() {
        return idJobSheet;
    }

    
    public void setIdJobSheet(Integer idJobSheet) {
        this.idJobSheet = idJobSheet;
    }

    
    public String getDnNo() {
        return dnNo;
    }

    
    public void setDnNo(String dnNo) {
        if (dnNo != null) {
            dnNo = dnNo.trim();
        }
        this.dnNo = dnNo;
    }

    
    public String getDestination() {
        return destination;
    }

    
    public void setDestination(String destination) {
        if (destination != null) {
            destination = destination.trim();
        }
        this.destination = destination;
    }

    
    public String getFlights() {
        return flights;
    }

    
    public void setFlights(String flights) {
        if (flights != null) {
            flights = flights.trim();
        }
        this.flights = flights;
    }

    
    public String getCntFlight() {
        return cntFlight;
    }

    
    public void setCntFlight(String cntFlight) {
        if (cntFlight != null) {
            cntFlight = cntFlight.trim();
        }
        this.cntFlight = cntFlight;
    }

    
    public String getFreightTerm() {
        return freightTerm;
    }

    
    public void setFreightTerm(String freightTerm) {
        if (freightTerm != null) {
            freightTerm = freightTerm.trim();
        }
        this.freightTerm = freightTerm;
    }

    
    public String getAgentTo() {
        return agentTo;
    }

    
    public void setAgentTo(String agentTo) {
        if (agentTo != null) {
            agentTo = agentTo.trim();
        }
        this.agentTo = agentTo;
    }

    
    public String getOperationStaff() {
        return operationStaff;
    }

    
    public void setOperationStaff(String operationStaff) {
        if (operationStaff != null) {
            operationStaff = operationStaff.trim();
        }
        this.operationStaff = operationStaff;
    }

    
    public String getTelpColoader() {
        return telpColoader;
    }

    
    public void setTelpColoader(String telpColoader) {
        if (telpColoader != null) {
            telpColoader = telpColoader.trim();
        }
        this.telpColoader = telpColoader;
    }

    
    public String getFaxColoader() {
        return faxColoader;
    }

    
    public void setFaxColoader(String faxColoader) {
        if (faxColoader != null) {
            faxColoader = faxColoader.trim();
        }
        this.faxColoader = faxColoader;
    }

    
    public String getPicColoader() {
        return picColoader;
    }

    
    public void setPicColoader(String picColoader) {
        if (picColoader != null) {
            picColoader = picColoader.trim();
        }
        this.picColoader = picColoader;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetai.mawb
     *
     * @return the value of jobsheetai.mawb
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getMawb() {
        return mawb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetai.mawb
     *
     * @param mawb the value for jobsheetai.mawb
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setMawb(String mawb) {
        if (mawb != null) {
            mawb = mawb.trim();
        }
        this.mawb = mawb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetai.hawb
     *
     * @return the value of jobsheetai.hawb
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getHawb() {
        return hawb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetai.hawb
     *
     * @param hawb the value for jobsheetai.hawb
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setHawb(String hawb) {
        if (hawb != null) {
            hawb = hawb.trim();
        }
        this.hawb = hawb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetai.epte
     *
     * @return the value of jobsheetai.epte
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getEpte() {
        return epte;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetai.epte
     *
     * @param epte the value for jobsheetai.epte
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setEpte(String epte) {
        if (epte != null) {
            epte = epte.trim();
        }
        this.epte = epte;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetai.pibNo
     *
     * @return the value of jobsheetai.pibNo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getPibNo() {
        return pibNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetai.pibNo
     *
     * @param pibNo the value for jobsheetai.pibNo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setPibNo(String pibNo) {
        if (pibNo != null) {
            pibNo = pibNo.trim();
        }
        this.pibNo = pibNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetai.dimention
     *
     * @return the value of jobsheetai.dimention
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getDimention() {
        return dimention;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetai.dimention
     *
     * @param dimention the value for jobsheetai.dimention
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setDimention(String dimention) {
        if (dimention != null) {
            dimention = dimention.trim();
        }
        this.dimention = dimention;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobsheetai.pickupCargo
     *
     * @return the value of jobsheetai.pickupCargo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getPickupCargo() {
        return pickupCargo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobsheetai.pickupCargo
     *
     * @param pickupCargo the value for jobsheetai.pickupCargo
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setPickupCargo(String pickupCargo) {
        if (pickupCargo != null) {
            pickupCargo = pickupCargo.trim();
        }
        this.pickupCargo = pickupCargo;
    }

    public String getCommodity() {
        return commodity;
    }

    public void setCommodity(String commodity) {
        this.commodity = commodity;
    }

    public String getBillTo() {
        return billTo;
    }

    public void setBillTo(String billTo) {
        this.billTo = billTo;
    }

    public String getCnNo() {
        return cnNo;
    }

    public void setCnNo(String cnNo) {
        this.cnNo = cnNo;
    }

    public String getBillToDebit() {
        return billToDebit;
    }

    public void setBillToDebit(String billToDebit) {
        this.billToDebit = billToDebit;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the jaminan
     */
    public String getJaminan() {
        return jaminan;
    }

    /**
     * @param jaminan the jaminan to set
     */
    public void setJaminan(String jaminan) {
        this.jaminan = jaminan;
    }
}
