package com.wings.persistence;


public class Jobtype extends JobtypeKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jobtype.description
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String description;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jobtype.description
     *
     * @return the value of jobtype.description
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jobtype.description
     *
     * @param description the value for jobtype.description
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setDescription(String description) {
        if (description != null) {
            description = description.trim();
        }
        this.description = description;
    }
}
