package com.wings.persistence;


public class KursdollarKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column kursdollar.idKursDollar
     *
     * @abatorgenerated Sat Jul 12 12:01:34 ICT 2008
     */
    private Integer idKursDollar;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column kursdollar.idKursDollar
     *
     * @return the value of kursdollar.idKursDollar
     *
     * @abatorgenerated Sat Jul 12 12:01:34 ICT 2008
     */
    public Integer getIdKursDollar() {
        return idKursDollar;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column kursdollar.idKursDollar
     *
     * @param idKursDollar the value for kursdollar.idKursDollar
     *
     * @abatorgenerated Sat Jul 12 12:01:34 ICT 2008
     */
    public void setIdKursDollar(Integer idKursDollar) {
        this.idKursDollar = idKursDollar;
    }
}
