package com.wings.persistence;

import java.util.Date;

public class Kursdollar extends KursdollarKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column kursdollar.changeDate
     *
     * @abatorgenerated Sat Jul 12 12:01:34 ICT 2008
     */
    private Date changeDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column kursdollar.value
     *
     * @abatorgenerated Sat Jul 12 12:01:34 ICT 2008
     */
    private Double value;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column kursdollar.changeDate
     *
     * @return the value of kursdollar.changeDate
     *
     * @abatorgenerated Sat Jul 12 12:01:34 ICT 2008
     */
    public Date getChangeDate() {
        return changeDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column kursdollar.changeDate
     *
     * @param changeDate the value for kursdollar.changeDate
     *
     * @abatorgenerated Sat Jul 12 12:01:34 ICT 2008
     */
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column kursdollar.value
     *
     * @return the value of kursdollar.value
     *
     * @abatorgenerated Sat Jul 12 12:01:34 ICT 2008
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column kursdollar.value
     *
     * @param value the value for kursdollar.value
     *
     * @abatorgenerated Sat Jul 12 12:01:34 ICT 2008
     */
    public void setValue(Double value) {
        this.value = value;
    }
}
