package com.wings.persistence;


public class PaymentKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column payment.idPayment
     *
     * @abatorgenerated Tue Sep 02 21:00:49 ICT 2008
     */
    private Integer idPayment;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column payment.idPayment
     *
     * @return the value of payment.idPayment
     *
     * @abatorgenerated Tue Sep 02 21:00:49 ICT 2008
     */
    public Integer getIdPayment() {
        return idPayment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column payment.idPayment
     *
     * @param idPayment the value for payment.idPayment
     *
     * @abatorgenerated Tue Sep 02 21:00:49 ICT 2008
     */
    public void setIdPayment(Integer idPayment) {
        this.idPayment = idPayment;
    }
}
