package com.wings.persistence;


public class Perkiraan extends PerkiraanKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column perkiraan.description
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    private String description;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column perkiraan.description
     *
     * @return the value of perkiraan.description
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column perkiraan.description
     *
     * @param description the value for perkiraan.description
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public void setDescription(String description) {
        if (description != null) {
            description = description.trim();
        }
        this.description = description;
    }
}
