package com.wings.persistence;


public class PerkiraanExample extends Perkiraan {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    private int idPerkiraan_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    private int description_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public int getIdPerkiraan_Indicator() {
        return idPerkiraan_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public void setIdPerkiraan_Indicator(int idPerkiraan_Indicator) {
        this.idPerkiraan_Indicator = idPerkiraan_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public int getDescription_Indicator() {
        return description_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table perkiraan
     *
     * @abatorgenerated Sat Jun 21 20:47:27 ICT 2008
     */
    public void setDescription_Indicator(int description_Indicator) {
        this.description_Indicator = description_Indicator;
    }
}
