package com.wings.persistence;


public class ShipperfeeKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipperfee.idShipperFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private Integer idShipperFee;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipperfee.idShipperFee
     *
     * @return the value of shipperfee.idShipperFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public Integer getIdShipperFee() {
        return idShipperFee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipperfee.idShipperFee
     *
     * @param idShipperFee the value for shipperfee.idShipperFee
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setIdShipperFee(Integer idShipperFee) {
        this.idShipperFee = idShipperFee;
    }
}
