package com.wings.persistence;


public class Shipper extends ShipperKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipper.name
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipper.description
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String description;
    private String description2;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipper.contactPerson
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String contactPerson;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipper.telp
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String telp;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipper.fax
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String fax;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipper.email
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipper.address1
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String address1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipper.address2
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String address2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipper.postalCode
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String postalCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipper.city
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String city;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shipper.region
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    private String region;
    
     private String npwp;
     private String _idAccountIDR = null;
     private String _idAccountUSD = null;
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipper.name
     *
     * @return the value of shipper.name
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipper.name
     *
     * @param name the value for shipper.name
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setName(String name) {
        if (name != null) {
            name = name.trim();
        }
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipper.description
     *
     * @return the value of shipper.description
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipper.description
     *
     * @param description the value for shipper.description
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setDescription(String description) {
        if (description != null) {
            description = description.trim();
        }
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipper.contactPerson
     *
     * @return the value of shipper.contactPerson
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipper.contactPerson
     *
     * @param contactPerson the value for shipper.contactPerson
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setContactPerson(String contactPerson) {
        if (contactPerson != null) {
            contactPerson = contactPerson.trim();
        }
        this.contactPerson = contactPerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipper.telp
     *
     * @return the value of shipper.telp
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getTelp() {
        return telp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipper.telp
     *
     * @param telp the value for shipper.telp
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setTelp(String telp) {
        if (telp != null) {
            telp = telp.trim();
        }
        this.telp = telp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipper.fax
     *
     * @return the value of shipper.fax
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipper.fax
     *
     * @param fax the value for shipper.fax
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setFax(String fax) {
        if (fax != null) {
            fax = fax.trim();
        }
        this.fax = fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipper.email
     *
     * @return the value of shipper.email
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipper.email
     *
     * @param email the value for shipper.email
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setEmail(String email) {
        if (email != null) {
            email = email.trim();
        }
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipper.address1
     *
     * @return the value of shipper.address1
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipper.address1
     *
     * @param address1 the value for shipper.address1
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setAddress1(String address1) {
        if (address1 != null) {
            address1 = address1.trim();
        }
        this.address1 = address1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipper.address2
     *
     * @return the value of shipper.address2
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipper.address2
     *
     * @param address2 the value for shipper.address2
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setAddress2(String address2) {
        if (address2 != null) {
            address2 = address2.trim();
        }
        this.address2 = address2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipper.postalCode
     *
     * @return the value of shipper.postalCode
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipper.postalCode
     *
     * @param postalCode the value for shipper.postalCode
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setPostalCode(String postalCode) {
        if (postalCode != null) {
            postalCode = postalCode.trim();
        }
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipper.city
     *
     * @return the value of shipper.city
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipper.city
     *
     * @param city the value for shipper.city
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setCity(String city) {
        if (city != null) {
            city = city.trim();
        }
        this.city = city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shipper.region
     *
     * @return the value of shipper.region
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shipper.region
     *
     * @param region the value for shipper.region
     *
     * @abatorgenerated Thu May 08 01:00:24 PDT 2008
     */
    public void setRegion(String region) {
        if (region != null) {
            region = region.trim();
        }
        this.region = region;
    }

    public String getNpwp() {
        return npwp;
    }

    public void setNpwp(String npwp) {
        this.npwp = npwp;
    }
   
    public String getIdAccountIDR() {
        return _idAccountIDR;
    }

    public void setIdAccountIDR(String idAccountIDR) {
        this._idAccountIDR = idAccountIDR;
    }

    public String getIdAccountUSD() {
        return _idAccountUSD;
    }

    public void setIdAccountUSD(String idAccountUSD) {
        this._idAccountUSD = idAccountUSD;
    }

    /**
     * @return the description2
     */
    public String getDescription2() {
        return description2;
    }

    /**
     * @param description2 the description2 to set
     */
    public void setDescription2(String description2) {
        this.description2 = description2;
    }
}
