package com.wings.persistence;


public class ShippinglineKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.idShippingLine
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String idShippingLine;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.idShippingLine
     *
     * @return the value of shippingLine.idShippingLine
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getIdShippingLine() {
        return idShippingLine;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.idShippingLine
     *
     * @param idShippingLine the value for shippingLine.idShippingLine
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setIdShippingLine(String idShippingLine) {
        if (idShippingLine != null) {
            idShippingLine = idShippingLine.trim();
        }
        this.idShippingLine = idShippingLine;
    }
}
