package com.wings.persistence;


public class Shippingline extends ShippinglineKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.name
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.description
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String description;
    private String description2;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.contactPerson
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String contactPerson;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.telp
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String telp;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.fax
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String fax;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.email
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.address1
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String address1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.address2
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String address2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.postalCode
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String postalCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.city
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String city;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.region
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String region;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.npwp
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String npwp;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.idAccountIDR
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String idAccountIDR;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shippingLine.idAccountUSD
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    private String idAccountUSD;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.name
     *
     * @return the value of shippingLine.name
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.name
     *
     * @param name the value for shippingLine.name
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setName(String name) {
        if (name != null) {
            name = name.trim();
        }
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.description
     *
     * @return the value of shippingLine.description
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.description
     *
     * @param description the value for shippingLine.description
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setDescription(String description) {
        if (description != null) {
            description = description.trim();
        }
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.contactPerson
     *
     * @return the value of shippingLine.contactPerson
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.contactPerson
     *
     * @param contactPerson the value for shippingLine.contactPerson
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setContactPerson(String contactPerson) {
        if (contactPerson != null) {
            contactPerson = contactPerson.trim();
        }
        this.contactPerson = contactPerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.telp
     *
     * @return the value of shippingLine.telp
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getTelp() {
        return telp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.telp
     *
     * @param telp the value for shippingLine.telp
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setTelp(String telp) {
        if (telp != null) {
            telp = telp.trim();
        }
        this.telp = telp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.fax
     *
     * @return the value of shippingLine.fax
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.fax
     *
     * @param fax the value for shippingLine.fax
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setFax(String fax) {
        if (fax != null) {
            fax = fax.trim();
        }
        this.fax = fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.email
     *
     * @return the value of shippingLine.email
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.email
     *
     * @param email the value for shippingLine.email
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setEmail(String email) {
        if (email != null) {
            email = email.trim();
        }
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.address1
     *
     * @return the value of shippingLine.address1
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.address1
     *
     * @param address1 the value for shippingLine.address1
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setAddress1(String address1) {
        if (address1 != null) {
            address1 = address1.trim();
        }
        this.address1 = address1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.address2
     *
     * @return the value of shippingLine.address2
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.address2
     *
     * @param address2 the value for shippingLine.address2
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setAddress2(String address2) {
        if (address2 != null) {
            address2 = address2.trim();
        }
        this.address2 = address2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.postalCode
     *
     * @return the value of shippingLine.postalCode
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.postalCode
     *
     * @param postalCode the value for shippingLine.postalCode
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setPostalCode(String postalCode) {
        if (postalCode != null) {
            postalCode = postalCode.trim();
        }
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.city
     *
     * @return the value of shippingLine.city
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.city
     *
     * @param city the value for shippingLine.city
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setCity(String city) {
        if (city != null) {
            city = city.trim();
        }
        this.city = city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.region
     *
     * @return the value of shippingLine.region
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.region
     *
     * @param region the value for shippingLine.region
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setRegion(String region) {
        if (region != null) {
            region = region.trim();
        }
        this.region = region;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.npwp
     *
     * @return the value of shippingLine.npwp
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getNpwp() {
        return npwp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.npwp
     *
     * @param npwp the value for shippingLine.npwp
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setNpwp(String npwp) {
        if (npwp != null) {
            npwp = npwp.trim();
        }
        this.npwp = npwp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.idAccountIDR
     *
     * @return the value of shippingLine.idAccountIDR
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getIdAccountIDR() {
        return idAccountIDR;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.idAccountIDR
     *
     * @param idAccountIDR the value for shippingLine.idAccountIDR
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setIdAccountIDR(String idAccountIDR) {
        if (idAccountIDR != null) {
            idAccountIDR = idAccountIDR.trim();
        }
        this.idAccountIDR = idAccountIDR;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shippingLine.idAccountUSD
     *
     * @return the value of shippingLine.idAccountUSD
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public String getIdAccountUSD() {
        return idAccountUSD;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shippingLine.idAccountUSD
     *
     * @param idAccountUSD the value for shippingLine.idAccountUSD
     *
     * @abatorgenerated Sat Sep 20 20:44:15 ICT 2008
     */
    public void setIdAccountUSD(String idAccountUSD) {
        if (idAccountUSD != null) {
            idAccountUSD = idAccountUSD.trim();
        }
        this.idAccountUSD = idAccountUSD;
    }

    /**
     * @return the description2
     */
    public String getDescription2() {
        return description2;
    }

    /**
     * @param description2 the description2 to set
     */
    public void setDescription2(String description2) {
        this.description2 = description2;
    }
}
