package com.wings.persistence;


public class TaxExample extends Tax {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    private int idTax_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    private int idJobSheet_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    private int noFaktur_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    private int fakturDate_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    private int dpp_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    private int ppn_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public int getIdTax_Indicator() {
        return idTax_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public void setIdTax_Indicator(int idTax_Indicator) {
        this.idTax_Indicator = idTax_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public int getIdJobSheet_Indicator() {
        return idJobSheet_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public void setIdJobSheet_Indicator(int idJobSheet_Indicator) {
        this.idJobSheet_Indicator = idJobSheet_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public int getNoFaktur_Indicator() {
        return noFaktur_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public void setNoFaktur_Indicator(int noFaktur_Indicator) {
        this.noFaktur_Indicator = noFaktur_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public int getFakturDate_Indicator() {
        return fakturDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public void setFakturDate_Indicator(int fakturDate_Indicator) {
        this.fakturDate_Indicator = fakturDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public int getDpp_Indicator() {
        return dpp_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public void setDpp_Indicator(int dpp_Indicator) {
        this.dpp_Indicator = dpp_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public int getPpn_Indicator() {
        return ppn_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public void setPpn_Indicator(int ppn_Indicator) {
        this.ppn_Indicator = ppn_Indicator;
    }
}
