package com.wings.persistence;


public class TaxKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column tax.idTax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    private Integer idTax;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column tax.idTax
     *
     * @return the value of tax.idTax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public Integer getIdTax() {
        return idTax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column tax.idTax
     *
     * @param idTax the value for tax.idTax
     *
     * @abatorgenerated Wed Jun 11 21:22:05 ICT 2008
     */
    public void setIdTax(Integer idTax) {
        this.idTax = idTax;
    }
}
