package com.wings.persistence;


public class Transporter extends TransporterKey {

  
    private String name;
    private String description;
    private String contactPerson;
    private String telp;
    private String fax;
    private String email;
    private String address1;
    private String address2;
    private String postalCode;
    private String city;
    private String region;
    private String npwp;
    private String idAccountIDR;
    private String idAccountUSD;
    
    public Transporter() {
        name = "";
        description = "";
        contactPerson = "";
        telp = "";
        fax = "";
        email = "";
        address1 = "";
        address2 = "";
        postalCode = "";
        city = "";
        region = "";
        npwp = "";
        idAccountIDR = "";
        idAccountUSD = "";
    }
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.name
     *
     * @param name the value for transporter.name
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setName(String name) {
        if (name != null) {
            name = name.trim();
        }
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.description
     *
     * @return the value of transporter.description
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.description
     *
     * @param description the value for transporter.description
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setDescription(String description) {
        if (description != null) {
            description = description.trim();
        }
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.contactPerson
     *
     * @return the value of transporter.contactPerson
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.contactPerson
     *
     * @param contactPerson the value for transporter.contactPerson
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setContactPerson(String contactPerson) {
        if (contactPerson != null) {
            contactPerson = contactPerson.trim();
        }
        this.contactPerson = contactPerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.telp
     *
     * @return the value of transporter.telp
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getTelp() {
        return telp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.telp
     *
     * @param telp the value for transporter.telp
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setTelp(String telp) {
        if (telp != null) {
            telp = telp.trim();
        }
        this.telp = telp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.fax
     *
     * @return the value of transporter.fax
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.fax
     *
     * @param fax the value for transporter.fax
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setFax(String fax) {
        if (fax != null) {
            fax = fax.trim();
        }
        this.fax = fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.email
     *
     * @return the value of transporter.email
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.email
     *
     * @param email the value for transporter.email
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setEmail(String email) {
        if (email != null) {
            email = email.trim();
        }
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.address1
     *
     * @return the value of transporter.address1
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.address1
     *
     * @param address1 the value for transporter.address1
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setAddress1(String address1) {
        if (address1 != null) {
            address1 = address1.trim();
        }
        this.address1 = address1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.address2
     *
     * @return the value of transporter.address2
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.address2
     *
     * @param address2 the value for transporter.address2
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setAddress2(String address2) {
        if (address2 != null) {
            address2 = address2.trim();
        }
        this.address2 = address2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.postalCode
     *
     * @return the value of transporter.postalCode
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.postalCode
     *
     * @param postalCode the value for transporter.postalCode
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setPostalCode(String postalCode) {
        if (postalCode != null) {
            postalCode = postalCode.trim();
        }
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.city
     *
     * @return the value of transporter.city
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.city
     *
     * @param city the value for transporter.city
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setCity(String city) {
        if (city != null) {
            city = city.trim();
        }
        this.city = city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.region
     *
     * @return the value of transporter.region
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.region
     *
     * @param region the value for transporter.region
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setRegion(String region) {
        if (region != null) {
            region = region.trim();
        }
        this.region = region;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.npwp
     *
     * @return the value of transporter.npwp
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getNpwp() {
        return npwp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.npwp
     *
     * @param npwp the value for transporter.npwp
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setNpwp(String npwp) {
        if (npwp != null) {
            npwp = npwp.trim();
        }
        this.npwp = npwp;
    }

    public String getIdAccountIDR() {
        return idAccountIDR;
    }

    public void setIdAccountIDR(String idAccountIDR) {
        this.idAccountIDR = idAccountIDR;
    }

    public String getIdAccountUSD() {
        return idAccountUSD;
    }

    public void setIdAccountUSD(String idAccountUSD) {
        this.idAccountUSD = idAccountUSD;
    }
}
