package com.wings.persistence;


public class TransporterKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column transporter.idTransporter
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    private String idTransporter;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transporter.idTransporter
     *
     * @return the value of transporter.idTransporter
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public String getIdTransporter() {
        return idTransporter;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transporter.idTransporter
     *
     * @param idTransporter the value for transporter.idTransporter
     *
     * @abatorgenerated Sun May 25 02:21:44 ICT 2008
     */
    public void setIdTransporter(String idTransporter) {
        if (idTransporter != null) {
            idTransporter = idTransporter.trim();
        }
        this.idTransporter = idTransporter;
    }
}
