package com.wings.persistence;


public class TransactionaccKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column transactionacc.idTransactionAcc
     *
     * @abatorgenerated Thu Jul 03 21:27:57 ICT 2008
     */
    private Integer idTransactionAcc;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column transactionacc.idTransactionAcc
     *
     * @return the value of transactionacc.idTransactionAcc
     *
     * @abatorgenerated Thu Jul 03 21:27:57 ICT 2008
     */
    public Integer getIdTransactionAcc() {
        return idTransactionAcc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column transactionacc.idTransactionAcc
     *
     * @param idTransactionAcc the value for transactionacc.idTransactionAcc
     *
     * @abatorgenerated Thu Jul 03 21:27:57 ICT 2008
     */
    public void setIdTransactionAcc(Integer idTransactionAcc) {
        this.idTransactionAcc = idTransactionAcc;
    }
}
